imie <- c("Krzysztof", "Maria", "Henryk", "Anna")
plec <- c("M", "K", "M", "K")
analiza <- c(3.5, 4.5, 5.0, 4.5)
algebra <- c(4.0, 5.0, 4.0, 3.5)
oceny <- data.frame(imie, plec, analiza, algebra)
cat("Podpunkt a:\n")
print(oceny)
cat("\nPodpunkt b:\n")
print(oceny[1:2,])
cat("\nPodpunkt c:\n")
str(oceny)
cat("\nPodpunkt d:\n")
print(mean(oceny$analiza))
cat("\nPodpunkt e:\n")
oceny$srednia <- apply(oceny[,3:4], 1, FUN=mean)
print(oceny)
cat("\nPodpunkt f:\n")
kobiety <- oceny[oceny["plec"] == "K",]
print(kobiety)
cat("\nPodpunkt g:\n")
dfG <- oceny[oceny["algebra"]>=4.5 | oceny["analiza"]>=4.5 ,]
print(dfG)
cat("\nPodpunkt h:\n")
vecH <- oceny[oceny["analiza"]>=4.5, ]
print(length(vecH[,1]))
